const std = @import("std");
const builtin = @import("builtin");

pub const word = c_long;
pub const unicode = c_ulong;

pub const CMBASE: word = 306;

pub const VALUE = 257;
pub const EVAL = 258;
pub const WHERE = 259;
pub const IF = 260;
pub const TO = 261;
pub const LEFTARROW = 262;
pub const COLONCOLON = 263;
pub const COLON2EQ = 264;
pub const TYPEVAR = 265;
pub const NAME = 266;
pub const CNAME = 267;
pub const CONST = 268;
pub const DOLLARS = 269;
pub const OFFSIDE = 270;
pub const ELSEQ = 271;
pub const ABSTYPE = 272;
pub const WITH = 273;
pub const DIAG = 274;
pub const EQEQ = 275;
pub const FREE = 276;
pub const INCLUDE = 277;
pub const EXPORT = 278;
pub const TYPE = 279;
pub const OTHERWISE = 280;
pub const SHOWSYM = 281;
pub const PATHNAME = 282;
pub const BNF = 283;
pub const LEX = 284;
pub const ENDIR = 285;
pub const ERRORSY = 286;
pub const ENDSY = 287;
pub const EMPTYSY = 288;
pub const READVALSY = 289;
pub const LEXDEF = 290;
pub const CHARCLASS = 291;
pub const ANTICHARCLASS = 292;
pub const LBEGIN = 293;
pub const ARROW = 294;
pub const PLUSPLUS = 295;
pub const MINUSMINUS = 296;
pub const DOTDOT = 297;
pub const VEL = 298;
pub const GE = 299;
pub const NE = 300;
pub const LE = 301;
pub const REM = 302;
pub const DIV = 303;
pub const INFIXNAME = 304;
pub const INFIXCNAME = 305;

pub const S = CMBASE + 0;
pub const K = CMBASE + 1;
pub const Y = CMBASE + 2;
pub const C = CMBASE + 3;
pub const B = CMBASE + 4;
pub const CB = CMBASE + 5;
pub const I = CMBASE + 6;
pub const HD = CMBASE + 7;
pub const TL = CMBASE + 8;
pub const BODY = CMBASE + 9;
pub const LAST = CMBASE + 10;
pub const S_p = CMBASE + 11;
pub const U = CMBASE + 12;
pub const Uf = CMBASE + 13;
pub const U_ = CMBASE + 14;
pub const Ug = CMBASE + 15;
pub const COND = CMBASE + 16;
pub const EQ = CMBASE + 17;
pub const NEQ = CMBASE + 18;
pub const NEG = CMBASE + 19;
pub const AND = CMBASE + 20;
pub const OR = CMBASE + 21;
pub const NOT = CMBASE + 22;
pub const APPEND = CMBASE + 23;
pub const STEP = CMBASE + 24;
pub const STEPUNTIL = CMBASE + 25;
pub const GENSEQ = CMBASE + 26;
pub const MAP = CMBASE + 27;
pub const ZIP = CMBASE + 28;
pub const TAKE = CMBASE + 29;
pub const DROP = CMBASE + 30;
pub const FLATMAP = CMBASE + 31;
pub const FILTER = CMBASE + 32;
pub const FOLDL = CMBASE + 33;
pub const MERGE = CMBASE + 34;
pub const FOLDL1 = CMBASE + 35;
pub const LIST_LAST = CMBASE + 36;
pub const FOLDR = CMBASE + 37;
pub const MATCH = CMBASE + 38;
pub const MATCHINT = CMBASE + 39;
pub const TRY = CMBASE + 40;
pub const SUBSCRIPT = CMBASE + 41;
pub const ATLEAST = CMBASE + 42;
pub const P = CMBASE + 43;
pub const B_p = CMBASE + 44;
pub const C_p = CMBASE + 45;
pub const S1 = CMBASE + 46;
pub const B1 = CMBASE + 47;
pub const C1 = CMBASE + 48;
pub const ITERATE = CMBASE + 49;
pub const ITERATE1 = CMBASE + 50;
pub const SEQ = CMBASE + 51;
pub const FORCE = CMBASE + 52;
pub const MINUS = CMBASE + 53;
pub const PLUS = CMBASE + 54;
pub const TIMES = CMBASE + 55;
pub const INTDIV = CMBASE + 56;
pub const FDIV = CMBASE + 57;
pub const MOD = CMBASE + 58;
pub const GR = CMBASE + 59;
pub const GRE = CMBASE + 60;
pub const POWER = CMBASE + 61;
pub const CODE = CMBASE + 62;
pub const DECODE = CMBASE + 63;
pub const LENGTH = CMBASE + 64;
pub const ARCTAN_FN = CMBASE + 65;
pub const EXP_FN = CMBASE + 66;
pub const ENTIER_FN = CMBASE + 67;
pub const LOG_FN = CMBASE + 68;
pub const LOG10_FN = CMBASE + 69;
pub const SIN_FN = CMBASE + 70;
pub const COS_FN = CMBASE + 71;
pub const SQRT_FN = CMBASE + 72;
pub const FILEMODE = CMBASE + 73;
pub const FILESTAT = CMBASE + 74;
pub const GETENV = CMBASE + 75;
pub const EXEC = CMBASE + 76;
pub const WAIT = CMBASE + 77;
pub const INTEGER = CMBASE + 78;
pub const SHOWNUM = CMBASE + 79;
pub const SHOWHEX = CMBASE + 80;
pub const SHOWOCT = CMBASE + 81;
pub const SHOWSCALED = CMBASE + 82;
pub const SHOWFLOAT = CMBASE + 83;
pub const NUMVAL = CMBASE + 84;
pub const STARTREAD = CMBASE + 85;
pub const STARTREADBIN = CMBASE + 86;
pub const NB_STARTREAD = CMBASE + 87;
pub const READVALS = CMBASE + 88;
pub const NB_READ = CMBASE + 89;
pub const READ = CMBASE + 90;
pub const READBIN = CMBASE + 91;
pub const GETARGS = CMBASE + 92;
pub const Ush = CMBASE + 93;
pub const Ush1 = CMBASE + 94;
pub const KI = CMBASE + 95;
pub const G_ERROR = CMBASE + 96;
pub const G_ALT = CMBASE + 97;
pub const G_OPT = CMBASE + 98;
pub const G_STAR = CMBASE + 99;
pub const G_FBSTAR = CMBASE + 100;
pub const G_SYMB = CMBASE + 101;
pub const G_ANY = CMBASE + 102;
pub const G_SUCHTHAT = CMBASE + 103;
pub const G_END = CMBASE + 104;
pub const G_STATE = CMBASE + 105;
pub const G_SEQ = CMBASE + 106;
pub const G_RULE = CMBASE + 107;
pub const G_UNIT = CMBASE + 108;
pub const G_ZERO = CMBASE + 109;
pub const G_CLOSE = CMBASE + 110;
pub const G_COUNT = CMBASE + 111;
pub const LEX_RPT = CMBASE + 112;
pub const LEX_RPT1 = CMBASE + 113;
pub const LEX_TRY = CMBASE + 114;
pub const LEX_TRY_ = CMBASE + 115;
pub const LEX_TRY1 = CMBASE + 116;
pub const LEX_TRY1_ = CMBASE + 117;
pub const DESTREV = CMBASE + 118;
pub const LEX_COUNT = CMBASE + 119;
pub const LEX_COUNT0 = CMBASE + 120;
pub const LEX_FAIL = CMBASE + 121;
pub const LEX_STRING = CMBASE + 122;
pub const LEX_CLASS = CMBASE + 123;
pub const LEX_CHAR = CMBASE + 124;
pub const LEX_DOT = CMBASE + 125;
pub const LEX_SEQ = CMBASE + 126;
pub const LEX_OR = CMBASE + 127;
pub const LEX_RCONTEXT = CMBASE + 128;
pub const LEX_STAR = CMBASE + 129;
pub const LEX_OPT = CMBASE + 130;
pub const MKSTRICT = CMBASE + 131;
pub const BADCASE = CMBASE + 132;
pub const CONFERROR = CMBASE + 133;
pub const ERROR = CMBASE + 134;
pub const FAIL = CMBASE + 135;
pub const False = CMBASE + 136;
pub const True = CMBASE + 137;
pub const NIL = CMBASE + 138;
pub const NILS = CMBASE + 139;
pub const UNDEF = CMBASE + 140;
pub const ATOMLIMIT = CMBASE + 141;

/// Heap-cell tag values. Non-exhaustive because GC marking temporarily negates
/// tag bytes (flips the sign bit) — those modified bytes are not valid enum tags.
pub const NodeTag = enum(u8) {
    ATOM = 0,
    DOUBLE = 1,
    DATAPAIR = 2,
    FILEINFO = 3,
    TVAR = 4,
    INT = 5,
    CONSTRUCTOR = 6,
    STRCONS = 7,
    ID = 8,
    AP = 9,
    LAMBDA = 10,
    CONS = 11,
    TRIES = 12,
    LABEL = 13,
    SHOW = 14,
    STARTREADVALS = 15,
    LET = 16,
    LETREC = 17,
    SHARE = 18,
    LEXER = 19,
    PAIR = 20,
    UNICODE = 21,
    TCONS = 22,
    _,
};

// Integer aliases kept for backward compatibility with make() calls and C ABI.
pub const ATOM = 0;
pub const DOUBLE = 1;
pub const DATAPAIR = 2;
pub const FILEINFO = 3;
pub const TVAR = 4;
pub const INT = 5;
pub const CONSTRUCTOR = 6;
pub const STRCONS = 7;
pub const ID = 8;
pub const AP = 9;
pub const LAMBDA = 10;
pub const CONS = 11;
pub const TRIES = 12;
pub const LABEL = 13;
pub const SHOW = 14;
pub const STARTREADVALS = 15;
pub const LET = 16;
pub const LETREC = 17;
pub const SHARE = 18;
pub const LEXER = 19;
pub const PAIR = 20;
pub const UNICODE = 21;
pub const TCONS = 22;

pub extern var SPACE: word;
pub const BACKSTOP: word = @as(word, 1) << (@bitSizeOf(word) - 1);
pub const tlptrbit = BACKSTOP;
pub const tlptrbits: word = @as(word, 3) << (@bitSizeOf(word) - 2);

pub const END = 0;
pub const GENERATOR = 0;
pub const GUARD = 1;
pub const REPEAT = 2;
pub const BUFSIZE = 1024;
pub const pnlim = 1024;

pub const undef_t = 0;
pub const bool_t = 1;
pub const num_t = 2;
pub const char_t = 3;
pub const list_t = 4;
pub const comma_t = 5;
pub const arrow_t = 6;
pub const void_t = 7;
pub const wrong_t = 8;
pub const bind_t = 9;
pub const type_t = 10;
pub const strict_t = 11;
pub const alias_t = 12;
pub const new_t = 13;
pub const hashsize = 512;

pub const algebraic_t = 0;
pub const synonym_t = 1;
pub const abstract_t = 2;
pub const placeholder_t = 3;
pub const free_t = 4;

pub const XBASE = ATOMLIMIT - 256;
pub const CHAR_X = XBASE;
pub const SHORT_X = XBASE + 1;
pub const INT_X = XBASE + 2;
pub const DBL_X = XBASE + 3;
pub const ID_X = XBASE + 4;
pub const AKA_X = XBASE + 5;
pub const HERE_X = XBASE + 6;
pub const CONSTRUCT_X = XBASE + 7;
pub const RV_X = XBASE + 8;
pub const PN_X = XBASE + 9;
pub const PN1_X = XBASE + 10;
pub const DEF_X = XBASE + 11;
pub const AP_X = XBASE + 12;
pub const CONS_X = XBASE + 13;
pub const TVAR_X = XBASE + 14;
pub const UNICODE_X = XBASE + 15;

pub const SIGNBIT = 0x10000000;
pub const MAXDIGIT = 0x7fff;
pub const UMAX = 0x10ffff;
pub const XVERSION = 83;

pub const ACT_NONE = 0;
pub const ACT_NEXTREDEX = 1;
pub const ACT_DONE = 2;

const main_clib = @import("main_clib.zig");
const heap_mod = @import("heap.zig");
const types_mod = @import("../compiler/types.zig");
const big_mod = @import("big.zig");
const lex_mod = @import("../parser/lex.zig");
const reduce_mod = @import("reduce.zig");
const trans_mod = @import("../compiler/trans.zig");
const repl_mod = @import("../driver/repl.zig");
const files_mod = @import("../io/files.zig");
pub const FILE = main_clib.FILE;
pub const sigjmp_buf = main_clib.sigjmp_buf;
pub const sigsetjmp = main_clib.sigsetjmp;
pub const siglongjmp = main_clib.siglongjmp;
pub const time_t = main_clib.time_t;
pub const DBL_MAX = main_clib.DBL_MAX;
pub const EOF = main_clib.EOF;
pub const EDOM = main_clib.EDOM;
pub const ERANGE = main_clib.ERANGE;
pub const O_RDONLY = main_clib.O_RDONLY;
pub const O_WRONLY = main_clib.O_WRONLY;
pub const O_CREAT = main_clib.O_CREAT;
pub const O_TRUNC = main_clib.O_TRUNC;
pub const STDOUT_FILENO = main_clib.STDOUT_FILENO;
pub const _SC_CLK_TCK = 3;
pub const SIGINT = main_clib.SIGINT;
pub const SIGBUS = main_clib.SIGBUS;
pub const SIGSEGV = main_clib.SIGSEGV;
pub const SIGTERM = main_clib.SIGTERM;
pub const SIGFPE = main_clib.SIGFPE;
pub const TIOCGWINSZ = main_clib.TIOCGWINSZ;
pub const RLIMIT_STACK = main_clib.RLIMIT_STACK;

pub const struct_tms = main_clib.struct_tms;
pub const struct_winsize = main_clib.struct_winsize;
pub const struct_rlimit = main_clib.struct_rlimit;

pub const stdin = main_clib.stdin;
pub const stdout = main_clib.stdout;
pub const stderr = main_clib.stderr;

pub const printf = main_clib.printf;
pub const fprintf = main_clib.fprintf;
pub const sprintf = main_clib.sprintf;
pub const snprintf = main_clib.snprintf;
pub const fscanf = main_clib.fscanf;
pub const sscanf = main_clib.sscanf;
pub const fputs = main_clib.fputs;
pub const fputc = main_clib.fputc;
pub const putc = main_clib.putc;
pub const putchar = main_clib.putchar;
pub const getc = main_clib.getc;
pub const getchar = main_clib.getchar;
pub const ungetc = main_clib.ungetc;
pub const fopen = main_clib.fopen;
pub const fdopen = main_clib.fdopen;
pub const fmemopen = main_clib.fmemopen;
pub const fclose = main_clib.fclose;
pub const fread = main_clib.fread;
pub const fwrite = main_clib.fwrite;
pub const fgets = main_clib.fgets;
pub const fileno = main_clib.fileno;
pub const setbuf = main_clib.setbuf;
pub const perror = main_clib.perror;

pub const malloc = main_clib.malloc;
pub const calloc = main_clib.calloc;
pub const realloc = main_clib.realloc;
pub const free = main_clib.free;
pub const exit = main_clib.exit;
pub const abort = main_clib.abort;
pub const getenv = main_clib.getenv;
pub const system = main_clib.system;
pub const chdir = main_clib.chdir;
pub const getcwd = main_clib.getcwd;
pub const fork = main_clib.fork;
pub const pipe = main_clib.pipe;
pub const dup2 = main_clib.dup2;
pub const close = main_clib.close;
pub const read = main_clib.read;
pub const write = main_clib.write;
pub const open = main_clib.open;
pub const unlink = main_clib.unlink;
pub const execl = main_clib.execl;
pub const wait = main_clib.wait;
pub const isatty = main_clib.isatty;
pub const ioctl = main_clib.ioctl;
pub const times = main_clib.times;
pub const sysconf = main_clib.sysconf;
pub const getrlimit = main_clib.getrlimit;
pub const setrlimit = main_clib.setrlimit;
pub const geteuid = main_clib.geteuid;
pub const getegid = main_clib.getegid;

pub const strlen = main_clib.strlen;
pub const strcmp = main_clib.strcmp;
pub const strncmp = main_clib.strncmp;
pub const strcpy = main_clib.strcpy;
pub const strncpy = main_clib.strncpy;
pub const strcat = main_clib.strcat;
pub const strncat = main_clib.strncat;
pub const strchr = main_clib.strchr;
pub const strrchr = main_clib.strrchr;
pub const strstr = main_clib.strstr;
pub const rindex = main_clib.rindex;

pub const isalpha = main_clib.isalpha;
pub const isalnum = main_clib.isalnum;
pub const isdigit = main_clib.isdigit;
pub const isxdigit = main_clib.isxdigit;
pub const isspace = main_clib.isspace;
pub const tolower = main_clib.tolower;

pub const localtime = main_clib.localtime;

pub const make = heap_mod.make;
pub inline fn cons(x: word, y: word) word {
    return make(CONS, x, y);
}
pub inline fn strcons(x: word, y: word) word {
    return make(STRCONS, x, y);
}
pub inline fn tries(x: word, y: word) word {
    return make(TRIES, x, y);
}
pub inline fn stosmallint(x: word) word {
    return make(INT, if (x < 0) SIGNBIT | -x else x, 0);
}
pub const sto_int = big_mod.sto_int;
pub const get_int = big_mod.get_int;
pub const sto_dbl = heap_mod.sto_dbl;
pub const get_dbl = heap_mod.get_dbl;
pub const setdbl = heap_mod.setdbl;
pub const bigtodbl = big_mod.bigtodbl;
pub const biglog = big_mod.biglog;
pub const biglog10 = big_mod.biglog10;
pub const bigcmp = big_mod.bigcmp;
pub const bigdiv = big_mod.bigdiv;
pub const bigmod = big_mod.bigmod;
pub const bignegate = big_mod.bignegate;
pub const bigplus = big_mod.bigplus;
pub const bigpow = big_mod.bigpow;
pub const bigscan = big_mod.bigscan;
pub const bigoscan = big_mod.bigoscan;
pub const bigxscan = big_mod.bigxscan;
pub const bigsub = big_mod.bigsub;
pub const bigtimes = big_mod.bigtimes;
pub const bigtostr = big_mod.bigtostr;
pub const bigtostr8 = big_mod.bigtostr8;
pub const bigtostrx = big_mod.bigtostrx;
pub const dbltobig = big_mod.dbltobig;
pub const strtobig = big_mod.strtobig;

pub const sto_char = heap_mod.sto_char;
pub const get_char = heap_mod.get_char;
pub const is_char = heap_mod.is_char;
pub const str_conv = lex_mod.str_conv;
pub const keep = lex_mod.keep;
pub const make_id = lex_mod.make_id;
pub const findid = lex_mod.findid;
pub const sto_id = heap_mod.sto_id;
pub const sto_pn = lex_mod.sto_pn;
pub const make_pn = lex_mod.make_pn;
pub const isconstrname = lex_mod.isconstrname;
pub const okid = lex_mod.okid;
pub const token = lex_mod.token;
pub const mallocfail = heap_mod.mallocfail;
pub const out = heap_mod.out;
pub const out_here = reduce_mod.out_here;
pub const output = reduce_mod.output;
pub const outstats = reduce_mod.outstats;
pub const getstring = reduce_mod.getstring;
pub const compare = reduce_mod.compare;
pub const reverse = heap_mod.reverse;
pub const append1 = heap_mod.append1;
pub const resetheap = heap_mod.resetheap;
pub const setupdic = lex_mod.setupdic;
pub const gc = heap_mod.gc;
pub const gcpatch = heap_mod.gcpatch;
pub const charname = heap_mod.charname;
pub const dump_script = heap_mod.dump_script;
pub const load_script = heap_mod.load_script;
pub const okdump = heap_mod.okdump;
pub const trueheapsize = heap_mod.trueheapsize;
pub const setprefix = heap_mod.setprefix;
pub const fm_time = files_mod.fm_time;
pub const parseline = repl_mod.parseline;
pub const process = repl_mod.process;
pub extern fn yyparse() c_int;
pub const yylex = lex_mod.yylex;
pub const layout = lex_mod.layout;
pub const setlmargin = lex_mod.setlmargin;
pub const unsetlmargin = lex_mod.unsetlmargin;
pub const openfile = lex_mod.openfile;
pub const rdline = lex_mod.rdline;
pub const addextn = lex_mod.addextn;
pub const adjust_prefix = lex_mod.adjust_prefix;
pub const dicovflo = lex_mod.dicovflo;
pub const mkprivate = lex_mod.mkprivate;
pub extern fn outUTF8(u: unicode, fil: ?*FILE) void;
pub extern fn fromUTF8(fil: ?*FILE) unicode;
pub const report_type = types_mod.report_type;
pub const out_type = types_mod.out_type;
pub const out_pattern = types_mod.out_pattern;
pub const printlist = types_mod.printlist;
pub const typesfirst = types_mod.typesfirst;
pub const instantiate = types_mod.instantiate;
pub const deps = types_mod.deps;
pub const add1 = types_mod.add1;
pub const member = types_mod.member;
pub const intersection = types_mod.intersection;
pub const setdiff = types_mod.setdiff;
pub const UNION = types_mod.UNION;
pub const subsumes = types_mod.subsumes;
pub extern fn make_typ(a: word, shf: word, class: word, info: word) word;
pub const block = trans_mod.block;
pub const compzf = trans_mod.compzf;
pub const declare = trans_mod.declare;
pub const declconstr = trans_mod.declconstr;
pub const decl_type = trans_mod.decl_type;
pub const genlhs = trans_mod.genlhs;
pub const irrefutable = trans_mod.irrefutable;
pub const mkshow = trans_mod.mkshow;
pub const redtvars = types_mod.redtvars;
pub const specify = trans_mod.specify;
pub const math_error = reduce_mod.math_error;
pub const int_error = reduce_mod.int_error;
pub const div_error = reduce_mod.div_error;
pub const fn_error = reduce_mod.fn_error;
pub const getenv_error = reduce_mod.getenv_error;
pub const subs_error = reduce_mod.subs_error;
pub const lexfail = reduce_mod.lexfail;
pub const lexstate = reduce_mod.lexstate;
pub const memclass = reduce_mod.memclass;
pub const g_residue = reduce_mod.g_residue;
pub const reduce_parse_close_error = reduce_mod.reduce_parse_close_error;
pub const piperrmess = reduce_mod.piperrmess;
pub const numplus = reduce_mod.numplus;

pub extern var yylval: word;
pub extern var yysterm: [*][*:0]u8;
pub extern var cmbnms: [*][*:0]u8;
