//! combinator.zig — the combinator/named-atom code → printed-name table.

const std = @import("std");
const word = @import("word.zig");

/// Combinator (and named-atom) code → printed name, indexed by `code - CMBASE`;
/// the reducer's graph printer uses it to name a combinator atom. Generated from
/// the historical `gencdecs` output. Order is significant — it must stay in
/// lock-step with the code numbering in `word.zig` (`S` = CMBASE+0,
/// `PLUS` = CMBASE+54, …, `NIL` = CMBASE+138). The trailing `null` (slot 141) is
/// the end sentinel; a new combinator is appended before it with a matching
/// `word.zig` constant at the same offset.
///
/// Tests: cmbnms aligns with the combinator codes in word.zig
pub const cmbnms: [142]?[*:0]const u8 = .{
    "S",
    "K",
    "Y",
    "C",
    "B",
    "CB",
    "I",
    "HD",
    "TL",
    "BODY",
    "LAST",
    "S_p",
    "U",
    "Uf",
    "U_",
    "Ug",
    "COND",
    "EQ",
    "NEQ",
    "NEG",
    "AND",
    "OR",
    "NOT",
    "APPEND",
    "STEP",
    "STEPUNTIL",
    "GENSEQ",
    "MAP",
    "ZIP",
    "TAKE",
    "DROP",
    "FLATMAP",
    "FILTER",
    "FOLDL",
    "MERGE",
    "FOLDL1",
    "LIST_LAST",
    "FOLDR",
    "MATCH",
    "MATCHINT",
    "TRY",
    "SUBSCRIPT",
    "ATLEAST",
    "P",
    "B_p",
    "C_p",
    "S1",
    "B1",
    "C1",
    "ITERATE",
    "ITERATE1",
    "SEQ",
    "FORCE",
    "MINUS",
    "PLUS",
    "TIMES",
    "INTDIV",
    "FDIV",
    "MOD",
    "GR",
    "GRE",
    "POWER",
    "CODE",
    "DECODE",
    "LENGTH",
    "ARCTAN_FN",
    "EXP_FN",
    "ENTIER_FN",
    "LOG_FN",
    "LOG10_FN",
    "SIN_FN",
    "COS_FN",
    "SQRT_FN",
    "FILEMODE",
    "FILESTAT",
    "GETENV",
    "EXEC",
    "WAIT",
    "INTEGER",
    "SHOWNUM",
    "SHOWHEX",
    "SHOWOCT",
    "SHOWSCALED",
    "SHOWFLOAT",
    "NUMVAL",
    "STARTREAD",
    "STARTREADBIN",
    "NB_STARTREAD",
    "READVALS",
    "NB_READ",
    "READ",
    "READBIN",
    "GETARGS",
    "Ush",
    "Ush1",
    "KI",
    "G_ERROR",
    "G_ALT",
    "G_OPT",
    "G_STAR",
    "G_FBSTAR",
    "G_SYMB",
    "G_ANY",
    "G_SUCHTHAT",
    "G_END",
    "G_STATE",
    "G_SEQ",
    "G_RULE",
    "G_UNIT",
    "G_ZERO",
    "G_CLOSE",
    "G_COUNT",
    "LEX_RPT",
    "LEX_RPT1",
    "LEX_TRY",
    "LEX_TRY_",
    "LEX_TRY1",
    "LEX_TRY1_",
    "DESTREV",
    "LEX_COUNT",
    "LEX_COUNT0",
    "LEX_FAIL",
    "LEX_STRING",
    "LEX_CLASS",
    "LEX_CHAR",
    "LEX_DOT",
    "LEX_SEQ",
    "LEX_OR",
    "LEX_RCONTEXT",
    "LEX_STAR",
    "LEX_OPT",
    "MKSTRICT",
    "BADCASE",
    "CONFERROR",
    "ERROR",
    "FAIL",
    "False",
    "True",
    "NIL",
    "NILS",
    "UNDEF",
    null,
};

test "cmbnms aligns with the combinator codes in word.zig" {
    // Spot-check the table's order against the code numbering it mirrors.
    const cases = .{
        .{ word.S, "S" },
        .{ word.PLUS, "PLUS" },
        .{ word.True, "True" },
        .{ word.NIL, "NIL" },
    };
    inline for (cases) |c| {
        const idx: usize = @intCast(c[0] - word.CMBASE);
        try std.testing.expectEqualStrings(c[1], std.mem.span(cmbnms[idx].?));
    }
}
