// Code generated by cmd/gencombinators; DO NOT EDIT.
package protocol

type Comb uint16

const (
	CombS            Comb = 0
	CombK            Comb = 1
	CombY            Comb = 2
	CombC            Comb = 3
	CombB            Comb = 4
	CombCB           Comb = 5
	CombI            Comb = 6
	CombHD           Comb = 7
	CombTL           Comb = 8
	CombBODY         Comb = 9
	CombLAST         Comb = 10
	CombS_p          Comb = 11
	CombU            Comb = 12
	CombUf           Comb = 13
	CombU_           Comb = 14
	CombUg           Comb = 15
	CombCOND         Comb = 16
	CombEQ           Comb = 17
	CombNEQ          Comb = 18
	CombNEG          Comb = 19
	CombAND          Comb = 20
	CombOR           Comb = 21
	CombNOT          Comb = 22
	CombAPPEND       Comb = 23
	CombSTEP         Comb = 24
	CombSTEPUNTIL    Comb = 25
	CombGENSEQ       Comb = 26
	CombMAP          Comb = 27
	CombZIP          Comb = 28
	CombTAKE         Comb = 29
	CombDROP         Comb = 30
	CombFLATMAP      Comb = 31
	CombFILTER       Comb = 32
	CombFOLDL        Comb = 33
	CombMERGE        Comb = 34
	CombFOLDL1       Comb = 35
	CombLIST_LAST    Comb = 36
	CombFOLDR        Comb = 37
	CombMATCH        Comb = 38
	CombMATCHINT     Comb = 39
	CombTRY          Comb = 40
	CombSUBSCRIPT    Comb = 41
	CombATLEAST      Comb = 42
	CombP            Comb = 43
	CombB_p          Comb = 44
	CombC_p          Comb = 45
	CombS1           Comb = 46
	CombB1           Comb = 47
	CombC1           Comb = 48
	CombITERATE      Comb = 49
	CombITERATE1     Comb = 50
	CombSEQ          Comb = 51
	CombFORCE        Comb = 52
	CombMINUS        Comb = 53
	CombPLUS         Comb = 54
	CombTIMES        Comb = 55
	CombINTDIV       Comb = 56
	CombFDIV         Comb = 57
	CombMOD          Comb = 58
	CombGR           Comb = 59
	CombGRE          Comb = 60
	CombPOWER        Comb = 61
	CombCODE         Comb = 62
	CombDECODE       Comb = 63
	CombLENGTH       Comb = 64
	CombARCTAN_FN    Comb = 65
	CombEXP_FN       Comb = 66
	CombENTIER_FN    Comb = 67
	CombLOG_FN       Comb = 68
	CombLOG10_FN     Comb = 69
	CombSIN_FN       Comb = 70
	CombCOS_FN       Comb = 71
	CombSQRT_FN      Comb = 72
	CombFILEMODE     Comb = 73
	CombFILESTAT     Comb = 74
	CombGETENV       Comb = 75
	CombEXEC         Comb = 76
	CombWAIT         Comb = 77
	CombINTEGER      Comb = 78
	CombSHOWNUM      Comb = 79
	CombSHOWHEX      Comb = 80
	CombSHOWOCT      Comb = 81
	CombSHOWSCALED   Comb = 82
	CombSHOWFLOAT    Comb = 83
	CombNUMVAL       Comb = 84
	CombSTARTREAD    Comb = 85
	CombSTARTREADBIN Comb = 86
	CombNB_STARTREAD Comb = 87
	CombREADVALS     Comb = 88
	CombNB_READ      Comb = 89
	CombREAD         Comb = 90
	CombREADBIN      Comb = 91
	CombGETARGS      Comb = 92
	CombUsh          Comb = 93
	CombUsh1         Comb = 94
	CombKI           Comb = 95
	CombG_ERROR      Comb = 96
	CombG_ALT        Comb = 97
	CombG_OPT        Comb = 98
	CombG_STAR       Comb = 99
	CombG_FBSTAR     Comb = 100
	CombG_SYMB       Comb = 101
	CombG_ANY        Comb = 102
	CombG_SUCHTHAT   Comb = 103
	CombG_END        Comb = 104
	CombG_STATE      Comb = 105
	CombG_SEQ        Comb = 106
	CombG_RULE       Comb = 107
	CombG_UNIT       Comb = 108
	CombG_ZERO       Comb = 109
	CombG_CLOSE      Comb = 110
	CombG_COUNT      Comb = 111
	CombLEX_RPT      Comb = 112
	CombLEX_RPT1     Comb = 113
	CombLEX_TRY      Comb = 114
	CombLEX_TRY_     Comb = 115
	CombLEX_TRY1     Comb = 116
	CombLEX_TRY1_    Comb = 117
	CombDESTREV      Comb = 118
	CombLEX_COUNT    Comb = 119
	CombLEX_COUNT0   Comb = 120
	CombLEX_FAIL     Comb = 121
	CombLEX_STRING   Comb = 122
	CombLEX_CLASS    Comb = 123
	CombLEX_CHAR     Comb = 124
	CombLEX_DOT      Comb = 125
	CombLEX_SEQ      Comb = 126
	CombLEX_OR       Comb = 127
	CombLEX_RCONTEXT Comb = 128
	CombLEX_STAR     Comb = 129
	CombLEX_OPT      Comb = 130
	CombMKSTRICT     Comb = 131
	CombBADCASE      Comb = 132
	CombCONFERROR    Comb = 133
	CombERROR        Comb = 134
	CombFAIL         Comb = 135
	CombFalse        Comb = 136
	CombTrue         Comb = 137
	CombNIL          Comb = 138
	CombNILS         Comb = 139
	CombUNDEF        Comb = 140
)

const CombBase int64 = 306

var CombNames = [...]string{
	"S",
	"K",
	"Y",
	"C",
	"B",
	"CB",
	"I",
	"HD",
	"TL",
	"BODY",
	"LAST",
	"S_p",
	"U",
	"Uf",
	"U_",
	"Ug",
	"COND",
	"EQ",
	"NEQ",
	"NEG",
	"AND",
	"OR",
	"NOT",
	"APPEND",
	"STEP",
	"STEPUNTIL",
	"GENSEQ",
	"MAP",
	"ZIP",
	"TAKE",
	"DROP",
	"FLATMAP",
	"FILTER",
	"FOLDL",
	"MERGE",
	"FOLDL1",
	"LIST_LAST",
	"FOLDR",
	"MATCH",
	"MATCHINT",
	"TRY",
	"SUBSCRIPT",
	"ATLEAST",
	"P",
	"B_p",
	"C_p",
	"S1",
	"B1",
	"C1",
	"ITERATE",
	"ITERATE1",
	"SEQ",
	"FORCE",
	"MINUS",
	"PLUS",
	"TIMES",
	"INTDIV",
	"FDIV",
	"MOD",
	"GR",
	"GRE",
	"POWER",
	"CODE",
	"DECODE",
	"LENGTH",
	"ARCTAN_FN",
	"EXP_FN",
	"ENTIER_FN",
	"LOG_FN",
	"LOG10_FN",
	"SIN_FN",
	"COS_FN",
	"SQRT_FN",
	"FILEMODE",
	"FILESTAT",
	"GETENV",
	"EXEC",
	"WAIT",
	"INTEGER",
	"SHOWNUM",
	"SHOWHEX",
	"SHOWOCT",
	"SHOWSCALED",
	"SHOWFLOAT",
	"NUMVAL",
	"STARTREAD",
	"STARTREADBIN",
	"NB_STARTREAD",
	"READVALS",
	"NB_READ",
	"READ",
	"READBIN",
	"GETARGS",
	"Ush",
	"Ush1",
	"KI",
	"G_ERROR",
	"G_ALT",
	"G_OPT",
	"G_STAR",
	"G_FBSTAR",
	"G_SYMB",
	"G_ANY",
	"G_SUCHTHAT",
	"G_END",
	"G_STATE",
	"G_SEQ",
	"G_RULE",
	"G_UNIT",
	"G_ZERO",
	"G_CLOSE",
	"G_COUNT",
	"LEX_RPT",
	"LEX_RPT1",
	"LEX_TRY",
	"LEX_TRY_",
	"LEX_TRY1",
	"LEX_TRY1_",
	"DESTREV",
	"LEX_COUNT",
	"LEX_COUNT0",
	"LEX_FAIL",
	"LEX_STRING",
	"LEX_CLASS",
	"LEX_CHAR",
	"LEX_DOT",
	"LEX_SEQ",
	"LEX_OR",
	"LEX_RCONTEXT",
	"LEX_STAR",
	"LEX_OPT",
	"MKSTRICT",
	"BADCASE",
	"CONFERROR",
	"ERROR",
	"FAIL",
	"False",
	"True",
	"NIL",
	"NILS",
	"UNDEF",
}
