// Command gencombinators generates the canonical Go combinator vocabulary.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
)

type entry struct {
	StableName  string   `json:"stable_name"`
	DisplayName string   `json:"display_name"`
	Aliases     []string `json:"aliases"`
	Offset      int      `json:"offset"`
	Value       int64    `json:"value"`
	Dispatch    string   `json:"dispatch"`
}

type schema struct {
	Schema  int     `json:"schema"`
	Base    int64   `json:"base"`
	Entries []entry `json:"entries"`
}

func main() {
	input := flag.String("input", "internal/protocol/combinators.json", "canonical JSON input")
	output := flag.String("output", "internal/protocol/combinator_generated.go", "generated Go output")
	flag.Parse()
	raw, err := os.ReadFile(*input)
	if err != nil {
		fatal(err)
	}
	var data schema
	if err := json.Unmarshal(raw, &data); err != nil {
		fatal(err)
	}
	if data.Schema != 1 || len(data.Entries) != 141 {
		fatal(fmt.Errorf("unsupported combinator schema or entry count"))
	}
	seen := map[string]bool{}
	var generated bytes.Buffer
	fmt.Fprintln(&generated, "// Code generated by internal/cmd/gencombinators; DO NOT EDIT.")
	fmt.Fprintln(&generated, "package protocol")
	fmt.Fprintln(&generated, "\ntype Comb uint16")
	fmt.Fprintln(&generated, "\nconst (")
	for index, item := range data.Entries {
		if item.Offset != index || item.Value != data.Base+int64(index) || item.StableName == "" || item.Dispatch == "" || seen[item.StableName] {
			fatal(fmt.Errorf("invalid combinator entry %d", index))
		}
		seen[item.StableName] = true
		fmt.Fprintf(&generated, "\tComb%s Comb = %d\n", item.StableName, item.Offset)
	}
	fmt.Fprintln(&generated, ")")
	fmt.Fprintf(&generated, "\nconst CombBase int64 = %d\n", data.Base)
	fmt.Fprintln(&generated, "\nvar CombNames = [...]string{")
	for _, item := range data.Entries {
		fmt.Fprintf(&generated, "\t%q,\n", item.DisplayName)
	}
	fmt.Fprintln(&generated, "}")
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "gencombinators:", err)
	os.Exit(1)
}
